apiKey: '服务器的apiKey'
url: '服务器的url'
# 单次创建的最大金额
maxPrice: 1000.0
# 单次创建的最小金额
minPrice: 1.0
# 高级设置
setting:
  # 游戏币倍率  这样就相当于是充值1块钱给100点券
  exchange: 100
  # 充值完成后执行的命令
  commands:
    # %pay_money% 为玩家本次充值的点券
    # %cny% 为玩家本次充值的金额
    # 可用动作
    # [player] 玩家执行命令,
    # [console] 控制台执行,
    # [tell] 给玩家发送一条消息,
    # [kether] 执行一个kether语句
    # [points] 数量 给在线全部人点券 支持运算 变量%pay_money%为玩家充值点券 %pay_money% * 0.0005 为玩家充值2000 奖励所有人1点券,
    - "[console] points give %player_name% %pay_money%"
    - "[tell] &7[&a&fMineSponsor&7] &7你充值的&a%pay_money%&7点券已到账  "
gui:
  # 告示牌设置
  sign: |
    &f
    &f请输入赞助金额
    &f输入完成后点击完成
  # 支付宝头颅设置
  ali:
    name: "&a支付宝"
    lore:
      - ""
  wx:
    name: "&a微信支付"
    lore:
      - ""